const FeaturedData = [
  {
    id: 1,
    make: 'chevy',
    category: 'american',
    img: 'img/car-default.jpeg',
    special: true,
    model: 'old model',
    price: '10000',
    type: 'classic',
    trans: 'manual',
    gas: '50',
  },
  {
    id: 2,
    make: 'mercedes',
    category: 'german',
    img: 'img/car-german-1.jpeg',
    special: true,
    model: 'new model',
    price: '100,000',
    type: 'coupe',
    trans: 'automatic',
    gas: '50',
  },
  {
    id: 3,
    make: 'bmw',
    category: 'german',
    img: 'img/car-german-2.jpeg',
    special: true,
    model: 'some model',
    price: '80,000',
    type: 'SUV',
    trans: 'automatic',
    gas: '50',
  },
  {
    id: 4,
    make: 'bmw',
    category: 'german',
    img: 'img/car-german-3.jpeg',
    special: true,
    model: 'new model',
    price: '70,000',
    type: 'sedan',
    trans: 'automatic',
    gas: '50',
  },
  {
    id: 5,
    make: 'bmw',
    category: 'german',
    img: 'img/car-german-4.jpeg',
    special: true,
    model: 'other model',
    price: '55,000',
    type: 'sedan',
    trans: 'automatic',
    gas: '50',
  },
]
export default FeaturedData
